CREATE OR REPLACE PACKAGE ASR_OWNER.PKG_CUSTOMER_LOAD AS
    PROCEDURE PROCESS_STAGING;
END PKG_CUSTOMER_LOAD;
/

CREATE OR REPLACE PACKAGE BODY ASR_OWNER.PKG_CUSTOMER_LOAD AS
    PROCEDURE PROCESS_STAGING IS
        v_start_time  TIMESTAMP := SYSTIMESTAMP;
        v_count       NUMBER := 0;
    BEGIN
        MERGE INTO TGT_TABLE t
        USING STG_TABLE s
        ON (t.CUSTOMER_EMAIL = s.CUSTOMER_EMAIL)
        WHEN MATCHED THEN
            UPDATE SET t.CUSTOMER_NAME = s.CUSTOMER_NAME,
                       t.SOURCE_SYSTEM = s.SOURCE_SYSTEM,
                       t.CUSTOMER_REVENUE = s.CUSTOMER_REVENUE,
                       t.CUSTOMER_CATEGORY = s.CUSTOMER_CATEGORY,
                       t.CUSTOMER_PHONE = s.CUSTOMER_PHONE,
                       t.CUSTOMER_COUNTRY = s.CUSTOMER_COUNTRY,
                       t.CUSTOMER_INDUSTRY = s.CUSTOMER_INDUSTRY
        WHEN NOT MATCHED THEN
            INSERT (CUSTOMER_NAME, CUSTOMER_EMAIL, SOURCE_SYSTEM, CREATED_DATE, CUSTOMER_REVENUE, CUSTOMER_CATEGORY, CUSTOMER_PHONE, CUSTOMER_COUNTRY, CUSTOMER_INDUSTRY)
            VALUES (s.CUSTOMER_NAME, s.CUSTOMER_EMAIL, s.SOURCE_SYSTEM, SYSDATE, s.CUSTOMER_REVENUE, s.CUSTOMER_CATEGORY, s.CUSTOMER_PHONE, s.CUSTOMER_COUNTRY, s.CUSTOMER_INDUSTRY);

        v_count := SQL%ROWCOUNT;
        COMMIT;

        INSERT INTO ETL_PROCESS_LOG (PROCESS_NAME, START_TIME, END_TIME, RECORDS_PROCESSED, STATUS)
        VALUES ('PROCESS_STAGING', v_start_time, SYSTIMESTAMP, v_count, 'COMPLETED');
        COMMIT;

        DBMS_OUTPUT.PUT_LINE('Processed ' || v_count || ' staging records');
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            INSERT INTO ETL_PROCESS_LOG (PROCESS_NAME, START_TIME, END_TIME, RECORDS_PROCESSED, STATUS)
            VALUES ('PROCESS_STAGING', v_start_time, SYSTIMESTAMP, 0, 'FAILED');
            COMMIT;
            RAISE;
    END PROCESS_STAGING;
END PKG_CUSTOMER_LOAD;
/
