CREATE OR REPLACE VIEW ASR_OWNER.VW_CUSTOMER_SUMMARY AS
SELECT c.CUSTOMER_ID,
       c.CUSTOMER_NAME,
       c.CUSTOMER_EMAIL,
       c.CUSTOMER_PHONE,
       c.SOURCE_SYSTEM,
       c.CREATED_DATE,
       c.MODIFIED_DATE,
       c.CUSTOMER_CATEGORY,
       c.CUSTOMER_REGION,
       c.CUSTOMER_INDUSTRY,
       FN_CUSTOMER_STATUS(c.CUSTOMER_ID) AS CUSTOMER_STATUS,
       (SELECT COUNT(*) FROM TGT_TABLE_AUDIT a WHERE a.CUSTOMER_ID = c.CUSTOMER_ID) AS AUDIT_COUNT
FROM TGT_TABLE c;
