ALTER TABLE STG_TABLE ADD (CUSTOMER_PHONE VARCHAR2(20));
ALTER TABLE STG_TABLE ADD (CUSTOMER_COUNTRY VARCHAR2(50));
ALTER TABLE TGT_TABLE ADD (CUSTOMER_PHONE VARCHAR2(20));
ALTER TABLE TGT_TABLE ADD (CUSTOMER_COUNTRY VARCHAR2(50));
