CREATE OR REPLACE PROCEDURE ASR_OWNER.SP_REFRESH_STAGING(
    p_days_old       IN NUMBER DEFAULT 30,
    p_records_deleted OUT NUMBER
)
IS
    v_start_time TIMESTAMP := SYSTIMESTAMP;
BEGIN
    DELETE FROM STG_TABLE
    WHERE PROCESS_FLAG = 'Y'
      AND LOAD_DATE < SYSDATE - p_days_old;

    p_records_deleted := SQL%ROWCOUNT;
    COMMIT;

    INSERT INTO ETL_PROCESS_LOG (PROCESS_NAME, START_TIME, END_TIME, RECORDS_LOADED, STATUS)
    VALUES ('REFRESH_STAGING', v_start_time, SYSTIMESTAMP, p_records_deleted, 'COMPLETED');
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        INSERT INTO ETL_PROCESS_LOG (PROCESS_NAME, START_TIME, END_TIME, RECORDS_LOADED, STATUS)
        VALUES ('REFRESH_STAGING', v_start_time, SYSTIMESTAMP, 0, 'FAILED');
        COMMIT;
        RAISE;
END SP_REFRESH_STAGING;
/
