CREATE OR REPLACE TRIGGER ASR_OWNER.TRG_CUSTOMER_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON ASR_OWNER.TGT_TABLE
FOR EACH ROW
DECLARE
    v_action VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
    ELSE
        v_action := 'DELETE';
    END IF;

    INSERT INTO ASR_OWNER.TGT_TABLE_AUDIT (
        CUSTOMER_ID, ACTION, CHANGED_BY, CHANGE_DATE,
        OLD_NAME, NEW_NAME
    ) VALUES (
        NVL(:NEW.CUSTOMER_ID, :OLD.CUSTOMER_ID),
        v_action,
        USER,
        SYSTIMESTAMP,
        :OLD.CUSTOMER_NAME,
        :NEW.CUSTOMER_NAME
    );
END TRG_CUSTOMER_AUDIT;
/
